# Como usar el array

Importamos la libreria de numpy para que podamos usarla

In [1]:
import numpy as np

Para crear un array de numpy solo necesitamos definir el **np.array** y pasarle como parametro una lista de python

In [2]:
lista = [1,2,3,4,5,6,7,8,9,10]
np_arr = np.array(lista)
np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Una matriz son varios Vectores o listas agrupadas una encima de la otra, es como una tabla de Excel

In [3]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices. Los elementos se empiezan a contar desde 0.
|Index  |  0|1|2|3|4|5|6|7|8|9|
|--|--| --|--|--|--|--|--|--|--|--|
|  Elemento| 1 | 2|3|4|5|6|7|8|9|10|

In [6]:
np_arr[9]

10

Es posible **operar** directamente con los elementos.

In [7]:
np_arr[4] + np_arr[1]

7

## Slicing

Nos permite extraer varios datos, tiene un comienzo y un final.

En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5.

In [8]:
np_arr[1:5]

array([2, 3, 4, 5])

Si no se ingresa el **valor de inicio**, se toma el inicio como la posición 0.

In [9]:
np_arr[:6]

array([1, 2, 3, 4, 5, 6])

En cambio, si no se le da una **posición final**, se regresan todos los elementos hasta el final del array.

In [10]:
np_arr[4:]

array([ 5,  6,  7,  8,  9, 10])

También se puede **trabajar por pasos**.

En este ejemplo de 3 en 3.
Regresa la posición 0, 0 + 3, 3 + 3 y como no hay posición 6 + 3, no se regrese nada.

In [11]:
np_arr[::3]

array([ 1,  4,  7, 10])

Cuando se le asigna un **valor negativo** se regresan los valores comenzando desde la última posición del array.

In [12]:
np_arr[-3:]

array([ 8,  9, 10])

Para el caso de las matrices, sucede algo similar.
Para acceder a los valores entre filas.

In [13]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

Para acceder a los valores entre filas y columnas.

In [14]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

## Reto

Crea una matriz de 3 dimensiones

* ¿Qué pudiste hacer?
* ¿Cómo hacer un Slicing de los datos?

Creacion de la lista 3d

In [16]:
lista_3d = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
matriz_3d = np.array(lista_3d)
matriz_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

El slicing se hace de la siguiente manera:
* 1ra pocicion estan las matrices anidadas en una pocicion
* 2ra pocicion estan la matriz en especifico que se trabajara
* 3ra pocicion estan los valores individuales de la matriz

In [25]:
matriz_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
matriz_3d[1:, 1:, 1:]

array([[[11, 12]]])