# Dimensiones


<img src="../Img/imgDimension.png">

* **scalar**: dim = 0 Un solo dato o valor
* **vector**: dim = 1 Listas de Python
* **matriz**: dim = 2 Hoja de cálculo
* **tensor**: dim > 3 Series de tiempo o Imágenes

## Declarando un escalar.
`.ndim` Nos muestra las dimensiones que tiene

In [1]:
import numpy as np

scalar = np.array(42)
print(scalar) 
scalar.ndim 

42


0

## Declarando un vector

In [2]:
vector = np.array([1, 2, 3])
print(vector) 
vector.ndim 

[1 2 3]


1

## Declarando una matriz.

In [3]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

## Declarando un tensor

In [2]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

## Agregar o eliminar dimensiones

Se puede definir el número de dimensiones desde la declaración del array

In [3]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

Se pueden expandir dimensiones a los array ya existentes con `expand_dims()`, **axis = 0 hace referencia a las filas**, mientras que **axis = 1 a las columnas**

In [4]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim 

[[1 2 3]]


2

Remover/comprimir las dimensiones que no están siendo usadas con `.squeeze()`

In [5]:
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Reto
* Definir un tensor de 5D


In [12]:
tensor_5 = np.array([1, 2, 3, 4, 5], ndmin= 5)
print(tensor_5)
tensor_5.ndim

[[[[[1 2 3 4 5]]]]]


5

* Sumarle una dimensión en cualquier eje

In [13]:
tensor_5 = np.expand_dims(tensor_5, axis=1)
tensor_5.ndim

6

* Borrar las dimensiones que no se usen

In [16]:
tensor_5 = np.squeeze(tensor_5)
tensor_5.ndim

1