# Shape
Indica la forma del arreglo

In [1]:
import numpy as np

arr = np.random.randint(1,10,(3,2))
arr.shape

(3, 2)

In [4]:
arr

array([[8, 2],
       [7, 6],
       [1, 2]])

# Reshape
Tranforma el array mientras se mantengan los elementos

In [5]:
np.reshape(arr, (1,6))

array([[8, 2, 7, 6, 1, 2]])

Se puede hacer un reshape como lo haría **C o Fortran**

Mientras con **C** los acomoda por filas
**Fortran** los acomoda por filas

In [9]:
np.reshape(arr,(2,3), 'C')


array([[8, 2, 7],
       [6, 1, 2]])

In [10]:
np.reshape(arr,(2,3), 'F')

array([[8, 1, 6],
       [7, 2, 2]])

## RETO

* Crear un array de cualquier dimensión y cambiar sus dimensiones

In [15]:
a = np.random.randint(1,10,(3,5,3))
a = np.reshape(a, (15,3))
a

array([[2, 5, 7],
       [3, 9, 9],
       [9, 7, 7],
       [2, 2, 2],
       [7, 7, 9],
       [2, 4, 5],
       [2, 9, 8],
       [7, 6, 6],
       [2, 9, 2],
       [7, 5, 1],
       [5, 8, 6],
       [9, 6, 1],
       [6, 5, 4],
       [3, 5, 1],
       [9, 5, 3]])

* Intenta cambiar el array de forma que no respete la estructura original

In [16]:
b = np.random.randint(1,10,(2,4))
b = np.reshape(b, (1,5)) 
# Da error y muestra que no se puede cambiar un array de logitud 8 a uno de (1,5)

ValueError: cannot reshape array of size 8 into shape (1,5)