# Funciones principales

En numpy hay varis funciones muy utiles para trabajar con ellos

**Documentacion**

* Estadistica: https://numpy.org/doc/stable/reference/routines.statistics.html
* Matematica: https://numpy.org/doc/stable/reference/routines.math.html

In [6]:
import numpy as np

arr = np.random.randint(1,20,10)

matriz = arr.reshape(2,5)
matriz

array([[10,  6,  5,  4, 11],
       [ 6,  7, 18, 18, 19]])

`.max` Para el máximo

In [8]:
print(arr.max())
print(matriz.max())

19


19

Podemos regresar los máximos de cada fila o columna especificando el eje
|0|Columnas  |
|--|--|
|  1|Filas  |

In [11]:
print(matriz.max(0))
print(matriz.max(1))
matriz

[10  7 18 18 19]
[11 19]


array([[10,  6,  5,  4, 11],
       [ 6,  7, 18, 18, 19]])

También tenemos `.argmax()` que nos devuelve la posición del elemento

En el caso de la matriz nos muestra con un 1 dónde se encuentra el mayor entre las columnas

De forma análoga tenemos `.min()`

In [12]:
arr.argmax()

9

In [15]:
matriz.argmax(0)

array([0, 1, 1, 1, 1], dtype=int64)

Podemos saber **la distancia entre** el valor más bajo con el más alto, con `.ptp()`

In [16]:
arr.ptp()

15

In [17]:
matriz.ptp(0)

array([ 4,  1, 13, 14,  8])

## Analisis estadistico

Ordenar elementos con `.sort()`

In [19]:
arr.sort()
arr

array([ 4,  5,  6,  6,  7, 10, 11, 18, 18, 19])

Obtener un percentil con `.percentile()`

In [22]:
np.percentile(arr, (25,75))

array([ 6.  , 16.25])

**Mediana:**

In [23]:
np.median(arr)

8.5

**Desviación estándar:**

In [24]:
np.std(arr)

5.571355310873647

**Varianza:**

In [25]:
np.var(arr)

31.04

**Promedio:**

In [26]:
np.mean(arr)

10.4

**Lo mismo aplica para las matrices**

In [28]:
np.median(matriz,1)

array([ 6., 18.])

## Concatenacion

Se pueden unir dos arrays, pero de los arrays de la misma dimension

In [29]:
a = np.array([[1,2], [3,4]])
b= np.array([5, 6])

Primero se debe poner a b con una dimension mas para poder concatenar

In [37]:
b = np.expand_dims(b, axis=0)

In [39]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

De igual manera se puede agregar en el otro eje pero para hacerlo se debe de poner la traspuesta de b para agregarlo como una columna

In [40]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])