**Documentacion**: https://numpy.org/doc/stable/reference/generated/numpy.copy.html

Esta funcion ayuda a **prevenir errores** a la hora de manipular datos

`.copy()` permite copiar un array de Numpy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original

In [2]:
import numpy as np

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Si tomamos un trozo del arrar con slice y queremos igualarlas a 0 estas se modificaran en el array original

In [3]:
trozo_arr = arr[0:6]

trozo_arr[:] = 0
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Con `.copy()` creamos una copia para no dañar el original

In [4]:
arr_copy = arr.copy()
arr_copy[:] = 100
print(arr_copy)
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[ 0  0  0  0  0  0  6  7  8  9 10]


Como dato tambien se puede copiar el array y hacer el slicing al mismo tiempo

In [5]:
arr_copy = arr.copy()[:6]
arr_copy

array([0, 0, 0, 0, 0, 0])