Las condiciones permiten hacer consultas mas especificas

In [4]:
import numpy as np

arr = np.arange(1,11, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Por ejemplo podemos regresar un array de booleanos donde la condicion se cumple

In [6]:
condicion = arr > 5
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Regresar los valores para donde la condicion se cumple con **True**

In [7]:
arr[condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

**Multiples conditiones**

In [8]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

Se puede modificar los valores que cumplan la condicion

In [10]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

Una funcion de condicines muy importante tambien es `.where()` donde pone una condicion, un valor por si se cumple y otro valor por si no

In [13]:
matriz = np.array([[19,  4, 43],
                   [ 8, 96, 80],
                   [ 6, 99, 35]])

np.where(matriz > 50, 0, 1)

array([[1, 1, 1],
       [1, 0, 0],
       [1, 0, 1]])