Hay diferentes operaciones que se pueden usar para los array de NumPy

Por ejemplo una lista de python entiende que quieres duplicar los datos, pero no es lo que se busca en este caso

In [1]:
lista = [1,2]
lista * 2

[1, 2, 1, 2]

NumPy lo que entiende es que lo que buscamos es multiplicar nuestro vector por un escalar

In [11]:
import numpy as np

arr = np.arange(1,11)
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Esto lo podemos hacer por todas lsa operaciones que se pueden realizar por un escalar

In [12]:
1 / arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [13]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Lo mismo aplica para las matrices

In [17]:

matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [18]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Una operacion muy importante en la ciencia de datos es la de punto por punto y hay dos formas de hacerla

In [19]:
np.matmul(matriz, matriz2.T)

array([[ 55, 130],
       [130, 330]])

In [20]:
matriz @ matriz2.T

array([[ 55, 130],
       [130, 330]])